# Generated by Django 4.0.3 on 2022-03-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='describtion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
